name: Proyecto_integradorV

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # â† Recomendado sobre windows-latest

    steps:
      - name: Paso 1 - Checkout del repositorio
        uses: actions/checkout@v4

      - name: Paso 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Paso 3 - Instalar dependencias del sistema
        run: sudo apt-get update && sudo apt-get install -y tzdata

      - name: Paso 4 - Instalar pip y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Paso 5 - Ejecutar Script principal
        env:
          PYTHONUNBUFFERED: 1
        run: |
          echo "Parchando yfinance para evitar bloqueo por User-Agent"
          echo "import yfinance as yf; yf.shared._DEFAULT_USER_AGENT = 'Mozilla/5.0'" > patch.py
          python patch.py
          python src/piv/main.py

      - name: Paso 6 - Commit y Push de cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Holan mundo action
          commit_user_name: Luisa Carvajal [GitHub Actions]
          commit_user_email: luisa.carvajal@iudigital.edu.co
          commit_author: Luisa Carvajal <luisa.carvajal@iudigital.edu.co>
